site_name: nextflow-zero2hero
site_author: Edoardo Giacopuzzi
repo_name: "HTGenomeAnalysisUnit/nextflow-zero2hero"
repo_url: "https://github.com/HTGenomeAnalysisUnit/nextflow-zero2hero.git"
edit_uri: ""
copyright: "The materials here are licensed under the MIT license"
theme:
  name: material
  logo: images/course_logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.sections
    - navigation.footer
  font:
    code: Roboto Mono
    text: Roboto
  palette:
    - scheme: default
      primary: green
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: green
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Practicals:
      - Introduction: practicals/index.md
      - Day 1:
          - Day1 Overview: practicals/day1/index.md
          - 1. Running a Nextflow pipeline: practicals/day1/1-nextflow-run-intro.md
      - Day 2:
          - Day2 Overview: practicals/day2/index.md
          - 1. Workflows: practicals/day2/1-workflows.md
      - Day 3:
          - Day3 Overview: practicals/day3/index.md
          - 1. Advanced configuration:
              - Advanced config intro: practicals/day3/1-advanced-config/index.md
              - Reference documentation: practicals/day3/1-advanced-config/reference_documentation.md
              - Practical exercises: practicals/day3/1-advanced-config/exercises.md
          - 2. Advanced publish: practicals/day3/2-advanced-publish.md
      - Day 4:
          - Day4 Overview: practicals/day4/index.md
          - 1. nf-core introduction: practicals/day4/1-nf-core-intro.md

  - Slides: slides.md

plugins:
  - search

markdown_extensions:
  - toc:
      toc_depth: 3
