site_name: nextflow-zero2hero
site_author: Edoardo Giacopuzzi
repo_name: "HTGenomeAnalysisUnit/nextflow-zero2hero"
repo_url: "https://github.com/HTGenomeAnalysisUnit/nextflow-zero2hero.git"
edit_uri: ""
copyright: "The materials here are licensed under the MIT license"
theme:
  name: material
  logo: images/course_logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.sections
    - navigation.footer
    - content.code.copy
  font:
    code: Roboto Mono
    text: Roboto
  palette:
    - scheme: default
      primary: green
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: green
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Practicals:
      - Introduction: practicals/index.md
      - Day 1:
          - Day1 Overview: practicals/day1/index.md
          - 1. Running a Nextflow pipeline: practicals/day1/1-nextflow-run-intro.md
          - 2. Workflow and channels basics: practicals/day1/2-basic-workflow.md
          - 3. Channels operators: practicals/day1/3-operators-playground.md
      - Day 2:
          - Day2 Overview: practicals/day2/index.md
          - 1. Workflows: practicals/day2/1-workflows.md
          - 2. Modules and subworkflows: practicals/day2/2-module-and-subworkflows.md
          - 3. Container basics: practicals/day2/3-containers-basics.md
          - 4. Using containers in Nextflow: practicals/day2/4-containers-nextflow.md
      - Day 3:
          - Day3 Overview: practicals/day3/index.md
          - 1. Advanced configuration:
              - Advanced config intro: practicals/day3/1-advanced-config/index.md
              - Reference documentation: practicals/day3/1-advanced-config/reference_documentation.md
              - Practical exercises: practicals/day3/1-advanced-config/exercises.md
          - 2. Advanced publish: practicals/day3/2-advanced-publish.md
          - 3. Best practices for pipeline structure: practicals/day3/3-best-practises-pipeline-structure.md
      - Day 4:
          - Day4 Overview: practicals/day4/index.md
          - 1. configure and launch nf-core pipeline: practicals/day4/1-configuring-launching-pipelines.md
          - 2. develop nf-core pipeline: practicals/day4/2-developing-pipeline.md
          - 3. contribute to nf-core: practicals/day4/3-contributing-to-nf-core.md

  - Slides: slides.md

plugins:
  - search

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.details
  - attr_list
  - toc:
      toc_depth: 3
