input_file : "${projectDir}/assets/test_input.tsv" 

reference_genome : "/processing_data/reference_datasets/iGenomes/2025.1/Homo_sapiens/NCBI/GRCh38/Sequence/BWAIndex/genome.fa"

outdir : "test_deepvariant_cpu_gvcf"

variant_chromosomes : "chr21,chr22"

variant_mode : "gvcf"

variant_caller : "deepvariant"

variant_caller_use_gpu : false

#igenomes_base : "/processing_data/reference_datasets/iGenomes/2025.1"
