title: "My quality report"
intro_text: "Cool, isn't it?"

show_analysis_paths: False
show_analysis_time: False

report_header_info:
  - Course: "NEXTLFOW - From zero to hero"
  - Title: "Best practices for pipeline structure"
  - Day: "3"
  - Session: 3

custom_logo: "assets/ht_logo.png"

